export default {
  openAppleHealth: () => {},
  requestPermissions: (params) =>
    Promise.resolve(),
  getWritePermissionStatus: (permission) =>
    Promise.resolve(false),
  isAvailable: false,
  getDateOfBirth: async () =>
    Promise.resolve(),
  addWorkout: (workout) =>
    Promise.resolve(),
  getWorkouts: async (startDate, endDate) =>
    Promise.resolve([]),
  getWorkoutsByMetadata: async (
    key,
    value,
  ) =>
    Promise.resolve([]),
  getWeights: async (unit, startDate, endDate) =>
    Promise.resolve([]),
  addWeight: async (weight, unit, date = null) =>
    Promise.resolve(),
  getDefaultSource: async () => Promise.resolve(null),
  getQuantity: async () => Promise.resolve([]),
  Constants: {
    writePermissionStatus: {
      authorized: '',
      denied: '',
      notDetermined: ''
    },
    units: {
      calories: '',
      kilo: '',
      pounds: '',
    },
    dataTypes: {
      dateOfBirth: '',
      workouts: '',
    },
    quantities: {
      bodyMassIndex: '',
      bodyFatPercentage: '',
      height: '',
      bodyMass: '',
      leanBodyMass: '',
      waistCircumference: '',
      stepCount: '',
      distanceWalkingRunning: '',
      distanceCycling: '',
      distanceWheelchair: '',
      basalEnergyBurned: '',
      activeEnergyBurned: '',
      flightsClimbed: '',
      nikeFuel: '',
      appleExerciseTime: '',
      pushCount: '',
      distanceSwimming: '',
      swimmingStrokeCount: '',
      VO2Max: '',
      distanceDownhillSnowSports: '',
      heartRate: '',
      bodyTemperature: '',
      basalBodyTemperature: '',
      bloodPressureSystolic: '',
      bloodPressureDiastolic: '',
      respiratoryRate: '',
      restingHeartRate: '',
      walkingHeartRateAverage: '',
      heartRateVariabilitySDNN: '',
      oxygenSaturation: '',
      peripheralPerfusionIndex: '',
      bloodGlucose: '',
      numberOfTimesFallen: '',
      electrodermalActivity: '',
      inhalerUsage: '',
      insulinDelivery: '',
      bloodAlcoholContent: '',
      forcedVitalCapacity: '',
      forcedExpiratoryVolume1: '',
      peakExpiratoryFlowRate: '',
      dietaryFatTotal: '',
      dietaryFatPolyunsaturated: '',
      dietaryFatMonounsaturated: '',
      dietaryFatSaturated: '',
      dietaryCholesterol: '',
      dietarySodium: '',
      dietaryCarbohydrates: '',
      dietaryFiber: '',
      dietarySugar: '',
      dietaryEnergyConsumed: '',
      dietaryProtein: '',
      dietaryVitaminA: '',
      dietaryVitaminB6: '',
      dietaryVitaminB12: '',
      dietaryVitaminC: '',
      dietaryVitaminD: '',
      dietaryVitaminE: '',
      dietaryVitaminK: '',
      dietaryCalcium: '',
      dietaryIron: '',
      dietaryThiamin: '',
      dietaryRiboflavin: '',
      dietaryNiacin: '',
      dietaryFolate: '',
      dietaryBiotin: '',
      dietaryPantothenicAcid: '',
      dietaryPhosphorus: '',
      dietaryIodine: '',
      dietaryMagnesium: '',
      dietaryZinc: '',
      dietarySelenium: '',
      dietaryCopper: '',
      dietaryManganese: '',
      dietaryChromium: '',
      dietaryMolybdenum: '',
      dietaryChloride: '',
      dietaryPotassium: '',
      dietaryCaffeine: '',
      dietaryWater: '',
      UVExposure: '',
    },
    workoutActivityTypes: {
      americanFootball: 0,
      archery: 0,
      australianFootball: 0,
      badminton: 0,
      barre: 0,
      baseball: 0,
      basketball: 0,
      bowling: 0,
      boxing: 0,
      climbing: 0,
      coreTraining: 0,
      cricket: 0,
      crossCountrySkiing: 0,
      crossTraining: 0,
      curling: 0,
      cycling: 0,
      dance: 0,
      downhillSkiing: 0,
      elliptical: 0,
      equestrianSports: 0,
      fencing: 0,
      fishing: 0,
      fitness: 0,
      flexibility: 0,
      functionalStrengthTraining: 0,
      golf: 0,
      gymnastics: 0,
      handball: 0,
      handCycling: 0,
      highIntensityIntervalTraining: 0,
      hiking: 0,
      hockey: 0,
      hunting: 0,
      jumpRope: 0,
      kickboxing: 0,
      lacrosse: 0,
      martialArts: 0,
      mindAndBody: 0,
      mixedCardio: 0,
      other: 0,
      paddleSports: 0,
      pilates: 0,
      play: 0,
      polo: 0,
      preparationAndRecovery: 0,
      racquetball: 0,
      rowing: 0,
      rugby: 0,
      running: 0,
      sailing: 0,
      skatingSports: 0,
      snowboarding: 0,
      snowSports: 0,
      soccer: 0,
      softball: 0,
      squash: 0,
      stairClimbing: 0,
      stairs: 0,
      stepTraining: 0,
      strengthTraining: 0,
      surfingSports: 0,
      swimming: 0,
      tableTennis: 0,
      taiChi: 0,
      tennis: 0,
      trackAndField: 0,
      typeWalking: 0,
      volleyball: 0,
      waterSports: 0,
      wheelchairRunPace: 0,
      wheelchairWalkPace: 0,
      wrestling: 0,
      yoga: 0,
    },
  },
};
